import { z } from 'zod'

export const personGeneralSchema = z.object({
  lastName: z.string().min(1, 'Обязательное поле'),
  firstName: z.string().min(1, 'Обязательное поле'),
  middleName: z.string().optional().default(''),
  birthDate: z.string().min(1, 'Обязательное поле').refine((v) => { const d = new Date(v); return !isNaN(d.getTime()) && d <= new Date() && d.getFullYear() >= 1900 }, 'Некорректная дата рождения'),
  birthPlace: z.string().optional().default(''),
  gender: z.enum(['male', 'female']),
  citizenship: z.string().min(1, 'Обязательное поле'),
  maritalStatus: z.string().min(1, 'Обязательное поле'),
  childrenCount: z.number().int().min(0).max(20),
  snils: z.string().regex(/^\d{3}-\d{3}-\d{3} \d{2}$/, 'Формат: 123-456-789 00').or(z.literal('')),
  inn: z.string().regex(/^\d{12}$/, 'ИНН — 12 цифр').or(z.literal('')),
  passportSeries: z.string().regex(/^\d{4}$/, 'Серия — 4 цифры').or(z.literal('')),
  passportNumber: z.string().regex(/^\d{6}$/, 'Номер — 6 цифр').or(z.literal('')),
  passportIssuedBy: z.string().optional().default(''),
  passportIssueDate: z.string().optional().default(''),
  passportDivisionCode: z.string().regex(/^\d{3}-\d{3}$/, 'Формат: 770-001').or(z.literal('')),
  phone: z.string().regex(/^[\d\s()+-]{6,20}$/, 'Некорректный телефон').or(z.literal('')),
  secondaryPhone: z.string().regex(/^[\d\s()+-]{6,20}$/, 'Некорректный телефон').or(z.literal('')),
  email: z.string().email('Некорректный email').optional().or(z.literal('')),
  preferredContact: z.string().min(1, 'Обязательное поле'),
  regCity: z.string().optional().default(''),
  regStreet: z.string().optional().default(''),
  regHouse: z.string().optional().default(''),
  regApartment: z.string().optional().default(''),
  regPostalCode: z.string().regex(/^\d{6}$/, 'Индекс — 6 цифр').or(z.literal('')),
  actualSameAsReg: z.boolean().default(true),
  actualAddress: z.string().optional().default(''),
  employmentStatus: z.string().min(1, 'Обязательное поле'),
  averageIncome: z.number().min(0).max(100000000),
  disabilityGroup: z.string().min(1, 'Обязательное поле'),
  benefitCategories: z.array(z.string()).default([]),
  isPensioner: z.boolean().default(false),
  isVeteran: z.boolean().default(false),
  isLargeFamily: z.boolean().default(false),
  status: z.string().min(1, 'Обязательное поле'),
  region: z.string().min(1, 'Обязательное поле'),
  notes: z.string().optional().default(''),
})
