import {
  APPEAL_SOURCE_LABELS,
  APPEAL_STATUS_LABELS,
  APPEAL_STATUS_COLORS,
  APPEAL_CATEGORIES,
  toOptions,
} from '@shared/config/dictionaries'

export const SOURCE_LABELS = APPEAL_SOURCE_LABELS
export const STATUS_LABELS = APPEAL_STATUS_LABELS
export const STATUS_COLORS = APPEAL_STATUS_COLORS
export const STATUS_OPTIONS = toOptions(APPEAL_STATUS_LABELS)
export const CATEGORY_OPTIONS = [...APPEAL_CATEGORIES]
